In [4]:
import pandas as pd
a=pd.DataFrame({'name':['a','b','c','d'],'department':['cs','it','cs','ec']})
pd.get_dummies(a,columns=['department'])

  name  department_cs  department_ec  department_it
0    a              1              0              0
1    b              0              0              1
2    c              1              0              0
3    d              0              1              0

In [5]:
print(a)

  name department
0    a         cs
1    b         it
2    c         cs
3    d         ec

In [6]:
pd.get_dummies(a,columns=['department'],drop_first=True)

  name  department_ec  department_it
0    a              0              0
1    b              0              1
2    c              0              0
3    d              1              0

In [7]:
import numpy as np
df=pd.DataFrame({'score':[10,30,40,70,90]})
df['result']=np.where(df['score']>70,'pass','fail')
df['grade']=np.where(df['score']>70,'A',np.where(df['score']>40,'B','C'))
print(df)

   score result grade
0     10   fail     C
1     30   fail     C
2     40   fail     C
3     70   fail     B
4     90   pass     A

In [12]:
from sklearn.model_selection import train_test_split
df=pd.DataFrame({'hours':[1,2,3,4,5],'score':[70,55,65,85,90]})
x=df[['hours']]
y=df[['score']]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
print(x_train)
print(x_test)

   hours
4      5
2      3
0      1
3      4
   hours
1      2

In [4]:
import pandas as pd
a=pd.read_csv('supermarket_sales.csv')
df=pd.DataFrame(a)
print(b)
df['cogs']=df['cogs'].fillna(df['cogs'].mean())
df.isnull().sum()

      Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female
1    226-31-3081      C  Naypyitaw        Normal  Female
2    631-41-3108      A     Yangon        Normal    Male
3    123-19-1176      A     Yangon        Member    Male
4    373-73-7910      A     Yangon        Normal    Male
..           ...    ...        ...           ...     ...
995  233-67-5758      C  Naypyitaw        Normal    Male
996  303-96-2227      B   Mandalay        Normal  Female
997  727-02-1313      A     Yangon        Member    Male
998  347-56-2442      A     Yangon        Normal    Male
999  849-09-3807      A     Yangon        Member  Female

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715
1    Electronic accessories       15.28         5   3.8200    80.2200
2        Home and lifestyle       46.33         7  16.2155   340.5255
3         Health and beauty       58.22         8  23.2880   489.0480
4         Sports and travel       86.31         7  30.2085   634.3785
..                      ...         ...       ...      ...        ...
995       Health and beauty       40.35         1   2.0175    42.3675
996      Home and lifestyle       97.38        10  48.6900  1022.4900
997      Food and beverages       31.84         1   1.5920    33.4320
998      Home and lifestyle       65.82         1   3.2910    69.1110
999     Fashion accessories       88.34         7  30.9190   649.2990

           Date   Time      Payment    cogs  gross margin percentage  \
0    01-05-2019  13:08      Ewallet  522.83                 4.761905
1    03-08-2019  10:29         Cash   76.40                 4.761905
2    03-03-2019  13:23  Credit card  324.31                 4.761905
3     1/27/2019  20:33      Ewallet  465.76                 4.761905
4    02-08-2019  10:37      Ewallet  604.17                 4.761905
..          ...    ...          ...     ...                      ...
995   1/29/2019  13:46      Ewallet   40.35                 4.761905
996  03-02-2019  17:16      Ewallet  973.80                 4.761905
997  02-09-2019  13:22         Cash   31.84                 4.761905
998   2/22/2019  15:33         Cash   65.82                 4.761905
999   2/18/2019  13:28         Cash  618.38                 4.761905

     gross income  Rating
0         26.1415     9.1
1          3.8200     9.6
2         16.2155     7.4
3         23.2880     8.4
4         30.2085     5.3
..            ...     ...
995        2.0175     6.2
996       48.6900     4.4
997        1.5920     7.7
998        3.2910     4.1
999       30.9190     6.6

[1000 rows x 17 columns]

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     5
dtype: int64

In [5]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [6]:
(df['Quantity']<3) & ((df['Rating']>8.5) | (df['Total']>600))

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [7]:
import seaborn as sns
from pd.plotting import parallel_coordinates
pd.parallel_coordinates(df,'Product line',cols=[''])

SyntaxError: invalid syntax (<ipython-input-7-b99520199791>, line 3)